config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise/sessions', registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: %i[create destroy]
  resources :user_recipes, only: %i[create index show destroy update] do
    resources :recipe_foods
  end
  resources :public_recipes, only: [:index]
  resources :shopping_list, only: [:index]
  # Defines the root path route ("/")
  root 'foods#index'
end

app/controllers/public_recipes_controller.rb
# frozen_string_literal: true

class PublicRecipesController < ApplicationController
  def index
    @recipes = UserRecipe.where(public: true).order(created_at: :desc)
  end
end

app/helpers/public_recipes_helper.rb
# frozen_string_literal: true

module PublicRecipesHelper
end

app/views/public_recipes/index.html.erb
<div class="container mt-4 w-75 mx-auto">
  <% if @recipes.empty? %>
    <h3 class="text-center text-danger">No recipes found</h3>
  <% end %>
  <% @recipes.each do |recipe| %>
    <%= link_to user_recipe_path(recipe.id),class:"text-decoration-none text-black" do %>
      <div class="card mb-2">
        <div class="card-body">
          <div class="d-flex justify-content-between mx-4">
            <div class="cols">
              <h5 class="card-title"><%= recipe.name %></h5>
              <small>by: <%= current_user.name%></small>
            </div>
            <div class="cols">
              <h5 class="card-title">Total foods items: <%= recipe.recipe_foods.includes(:food).count%></h5>
              <small>
                <% sum = 0 %>
                <% recipe.recipe_foods.includes(:food).each do |food| %>
                  <% sum += food.quantity * food.food.price %>
                <% end %>
                <%= "Total price: $#{sum}" %>
              </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>