config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise/sessions', registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: %i[create destroy]
  resources :user_recipes, only: %i[create index show destroy update] do
    resources :recipe_foods
  end
  resources :public_recipes, only: [:index]
  resources :shopping_list, only: [:index]
  # Defines the root path route ("/")
  root 'foods#index'
end

app/models/user_recipe.rb
# frozen_string_literal: true

class UserRecipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  def self.created_by_current_user(current_user)
    where(user_id: current_user.id).order(created_at: :desc)
  end

  def self.public_recipes_ordered_by_newest
    where(public: true).order(created_at: :desc)
  end
end

app/controllers/user_recipes_controller.rb
# frozen_string_literal: true

class UserRecipesController < ApplicationController
  load_and_authorize_resource
  def new
    @recipe = UserRecipe.new
  end

  def create
    @user = current_user
    @recipe = @user.user_recipes.new(recipes_params)
    @recipe.public = false
    if @recipe.save
      redirect_to user_recipes_path, notice: 'recipe was successfully created'
    else
      render :new, alert: "Couldn't create recipe for user"
    end
  end

  def index
    @recipes = UserRecipe.all
  end

  def show
    @recipe = UserRecipe.find(params[:id])
    @user = current_user
    @recipe_foods = RecipeFood.includes(:food).where(user_recipe_id: @recipe.id)
  end

  def destroy
    @recipe = UserRecipe.find(params[:id])
    @recipe.destroy
    redirect_to user_recipes_path, notice: 'Recipe was successfully deleted'
  end

  def update
    @recipe = UserRecipe.find(params[:id])

    if @recipe.public == true
      @recipe.update(public: false)
    else
      UserRecipe.find(@recipe.id).update(public: true)
    end
    redirect_to user_recipe_path(@recipe.id), notice: 'Public Updated'
  end

  private

  def recipes_params
    params.permit(:name, :description, :preparation_time, :cooking_time, current_user.id)
  end
end

app/helpers/user_recipes_helper.rb
# frozen_string_literal: true

module UserRecipesHelper
end

app/views/user_recipes/index.html.erb
<div class="container">
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary me-3 my-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add Recipe
  </button>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Add Recipe</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= form_with model: @recipe, url: user_recipes_path do |f| %>
            <div class="form-group mb-2">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group mb-2">
              <%= f.label :description %>
              <%= f.text_area :description, size: '50x10', class: "form-control" %>
            </div>
            <div class="form-group mb-2">
              <%= f.label :preparation_time %>
              <%= f.text_field :preparation_time, class: "form-control" %>
              <em>Eg: 1 Hour</em>
            </div>
            <div class="form-group mb-2">
              <%= f.label :cooking_time %>
              <%= f.text_field :cooking_time, class: "form-control" %>
              <em>Eg: 1 Hour</em>
            </div>
            <div class="form-group mb-2 ">
              <%= f.submit "Create Recipe", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% @recipes.each do |recipe| %>
    <%= link_to user_recipe_path(recipe.id),class:"text-decoration-none text-black" do %>
      <div class="card mb-3">
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <h2><%= recipe.name %></h2>
              <% if can? :destroy, recipe %>
                <%= button_to "Delete", user_recipe_path(recipe.id), class:"btn btn-outline-danger", method: :delete %>
              <% end %>
            </div>
            <div class="col-md-8">
              <p><%= recipe.description %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/user_recipes/new.html.erb
<div class="recipe-new">
    <%= form_with model: @user_recipes, url: user_recipes_path, method: :post, scope: :user_recipe do |f| %>

        <div>
            <div>
                <%= f.label :name %> <br>
                <%= f.text_field :name %>
            </div>

            <div>
                <%= f.label :preparation_time_in_mins %> <br>
                <%= f.number_field :preparation_time, step: 0.01, min: 0  %>
            </div>

            <div>
                <%= f.label :cooking_time_in_mins %> <br>
                <%= f.number_field :cooking_time, step: 0.01, min: 0 %>
            </div>

            <div>
                <%= f.label :public %>
                <%= f.radio_button :public, true %> Yes
                <%= f.radio_button :public, false %> No
            </div>

            <div>
                <%= f.label :description %> <br>
                <%= f.text_area :description %>
            </div>

            <%= f.submit 'Create Recipe' %> <br>
        </div>

    <% end %>
</div>

app/views/user_recipes/show.html.erb
<div class="container">
  <h1 class="text-center my-2"><%= @recipe.name %></h1>
  <div class="row mt-2 d-flex justify-content-center">
    <div class="col-md-8">
      <p>Preparation Time: <%= @recipe.preparation_time %></p>
      <p>Preparation Time: <%= @recipe.cooking_time %></p>
      <p>Step go here...</p>
    </div>
    <div class="col-md-4">
        <%= form_with model:@recipe, url:user_recipe_path(@recipe.id), html:{method: :put} do |f| %>
            <div class="form-check form-switch">
              <%= f.label :public, class:"form-check-label" %>
              <%= f.check_box :public, class:"form-check-input", onchange: "this.form.submit()" %>
            </div>
        <% end %>
    </div>
  </div>
  <div class="row">
    <% if @recipe.user_id != @user.id  && @recipe.public == false %>
      <div class="col-md-12">
        <h3 class="text-center">This recipe is private</h3>
      </div>
    <% else %>

        <div class="col-md-8">
          <%= link_to 'General shopping list', shopping_list_index_path, class: 'btn btn-primary' %>
        </div>
        <div class="col-md-4">
        <% if @recipe.public == true %>
          <%= link_to 'Add Ingredient', new_user_recipe_recipe_food_path(@recipe.id), class: 'btn btn-primary' %>
        <% end %>
        </div>
   
      <table class="table table-hover table-bordered mt-4 table-responsive{-sm|-md|-lg|-xl} ">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Value</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe_foods.each do |food| %>
            <tr>
              <td><%= food.food.name%></td>
              <td><%= food.quantity%><%= food.food.measurement_unit %></td>
              <td>
                <% sum = 0 %>
                <% sum += food.quantity * food.food.price %>
                <%= "Total price: $#{sum}" %>
              </td>
              <td>
              <% if can? :destroy, @recipe %>
                  <%= button_to "Delete", user_recipe_recipe_food_path(user_recipe_id:@recipe.id,id:food.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
              <% end %>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
    <% end %>
  </div>
</div>