config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise/sessions', registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: %i[create destroy]
  resources :user_recipes, only: %i[create index show destroy update] do
    resources :recipe_foods
  end
  resources :public_recipes, only: [:index]
  resources :shopping_list, only: [:index]
  # Defines the root path route ("/")
  root 'foods#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role == 'admin'
      can :manage, :all
    else
      can %i[update destroy], UserRecipe, user_id: user.id
      can %i[destroy], Food, user_id: user.id
      can :create, Food
      can :create, UserRecipe
      can :create, RecipeFood
      can :destroy, RecipeFood
      can :read, :all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
# frozen_string_literal: true

class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
end

app/models/recipe_food.rb
# frozen_string_literal: true

class RecipeFood < ApplicationRecord
  belongs_to :user_recipe
  belongs_to :food
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :user_recipes

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :name, presence: true
end

app/models/user_recipe.rb
# frozen_string_literal: true

class UserRecipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  def self.created_by_current_user(current_user)
    where(user_id: current_user.id).order(created_at: :desc)
  end

  def self.public_recipes_ordered_by_newest
    where(public: true).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/foods_controller.rb
# frozen_string_literal: true

class FoodsController < ApplicationController
  load_and_authorize_resource
  def index
    @foods = Food.all
  end

  def new
    @user = current_user
    @food = Food.new
  end

  def create
    @user = current_user
    @food = Food.new(food_params)
    @food.user = @user
    if @food.save
      redirect_to root_path, notice: 'Food was successfully created.'
    else
      render :new, alert: 'Food was not created.'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to root_path, notice: 'Food was successfully deleted.'
  end

  def food_params
    params.permit(:name, :measurement_unit, :price, :quantity, current_user.id)
  end
end

app/controllers/public_recipes_controller.rb
# frozen_string_literal: true

class PublicRecipesController < ApplicationController
  def index
    @recipes = UserRecipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
# frozen_string_literal: true

class RecipeFoodsController < ApplicationController
  load_and_authorize_resource
  def index
    @foods = current_user.recipes_foods.select(:food_id, 'SUM(quantity) as quantity').group(:food_id, :quantity)
    @sum = 0
    @foods.each do |food|
      @sum += food.quantity * food.food.price
    end
  end

  def create
    @user = current_user
    @recipe = UserRecipe.find(params[:user_recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipes_foods_params)
    if @recipe_food.save
      redirect_to user_recipe_path(params[:user_recipe_id]), notice: 'Food was successfully added'
    else
      render :new, alert: "Couldn't add food to recipe"
    end
  end

  def new
    @foods = Food.all
    @food_items = []
    @foods.each do |food|
      @food_items << [food.name, food.id]
    end
    @recipe = UserRecipe.find(params[:user_recipe_id])
  end

  def destroy
    @user = current_user
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    return unless @recipe_food.destroy

    redirect_to user_recipe_path(params[:user_recipe_id]), notice: 'Food was successfully deleted'
  end

  # Only allow a list of trusted parameters through.
  def recipes_foods_params
    params.require(:@recipe_food).permit(:food_id, :user_recipe_id, :quantity)
  end
end

app/controllers/shopping_list_controller.rb
# frozen_string_literal: true

class ShoppingListController < ApplicationController
  def index
    @user = current_user
    @foods = Food.all
    @recipes = UserRecipe.where(user_id: @user.id)
    @recipe_foods = RecipeFood.where(user_recipe_id: @recipes.ids)
    @shopping_list = []
    @recipe_foods.each do |recipe_food|
      @shopping_list << recipe_food
    end
    @final_list = @foods.where(id: @shopping_list.map(&:food_id))

    @price = @final_list.pluck(:price)
    @quantity = @final_list.pluck(:quantity)
    @total = @price.zip(@quantity).map { |x, y| x * y }.sum
  end
end

app/controllers/user_recipes_controller.rb
# frozen_string_literal: true

class UserRecipesController < ApplicationController
  load_and_authorize_resource
  def new
    @recipe = UserRecipe.new
  end

  def create
    @user = current_user
    @recipe = @user.user_recipes.new(recipes_params)
    @recipe.public = false
    if @recipe.save
      redirect_to user_recipes_path, notice: 'recipe was successfully created'
    else
      render :new, alert: "Couldn't create recipe for user"
    end
  end

  def index
    @recipes = UserRecipe.all
  end

  def show
    @recipe = UserRecipe.find(params[:id])
    @user = current_user
    @recipe_foods = RecipeFood.includes(:food).where(user_recipe_id: @recipe.id)
  end

  def destroy
    @recipe = UserRecipe.find(params[:id])
    @recipe.destroy
    redirect_to user_recipes_path, notice: 'Recipe was successfully deleted'
  end

  def update
    @recipe = UserRecipe.find(params[:id])

    if @recipe.public == true
      @recipe.update(public: false)
    else
      UserRecipe.find(@recipe.id).update(public: true)
    end
    redirect_to user_recipe_path(@recipe.id), notice: 'Public Updated'
  end

  private

  def recipes_params
    params.permit(:name, :description, :preparation_time, :cooking_time, current_user.id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/foods_helper.rb
# frozen_string_literal: true

module FoodsHelper
end

app/helpers/public_recipes_helper.rb
# frozen_string_literal: true

module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
# frozen_string_literal: true

module RecipeFoodsHelper
end

app/helpers/shopping_list_helper.rb
# frozen_string_literal: true

module ShoppingListHelper
end

app/helpers/user_recipes_helper.rb
# frozen_string_literal: true

module UserRecipesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <%= render "shared/navbar" %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Add Food</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
           <%= form_with model: @food, url: foods_path do |f| %>
            <div class="form-group mb-2">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group mb-2">
              <%= f.label :measurement_unit %>
              <%= f.text_field :measurement_unit, class: "form-control" %>
            </div>
            <div class="form-group mb-2">
              <%= f.label :price %>
              <%= f.text_field :price, class: "form-control" %>
            </div>
            <div class="form-group mb-2">
              <%= f.label :quantity %>
              <%= f.text_field :quantity, class: "form-control" %>
            </div>
            <div class="form-group mb-2 ">
              <%= f.submit "Create Food", class: "btn btn-primary" %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Recipe-App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Food", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Recipes", user_recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Public Recipes", public_recipes_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
            <%= link_to "Shopping List",shopping_list_index_path, class:"nav-link active" %>
        </li>
      </ul>
      <% if user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, class:"btn btn-outline-danger", method: :delete%>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item mx-2">
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>