config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise/sessions', registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: %i[create destroy]
  resources :user_recipes, only: %i[create index show destroy update] do
    resources :recipe_foods
  end
  resources :public_recipes, only: [:index]
  resources :shopping_list, only: [:index]
  # Defines the root path route ("/")
  root 'foods#index'
end

app/models/food.rb
# frozen_string_literal: true

class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
end

app/controllers/foods_controller.rb
# frozen_string_literal: true

class FoodsController < ApplicationController
  load_and_authorize_resource
  def index
    @foods = Food.all
  end

  def new
    @user = current_user
    @food = Food.new
  end

  def create
    @user = current_user
    @food = Food.new(food_params)
    @food.user = @user
    if @food.save
      redirect_to root_path, notice: 'Food was successfully created.'
    else
      render :new, alert: 'Food was not created.'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to root_path, notice: 'Food was successfully deleted.'
  end

  def food_params
    params.permit(:name, :measurement_unit, :price, :quantity, current_user.id)
  end
end

app/helpers/foods_helper.rb
# frozen_string_literal: true

module FoodsHelper
end

app/views/foods/index.html.erb
<div class="container mt-1">
  <!-- Button trigger modal -->
  <button type="button" class="btn-sm btn btn-primary me-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add food
  </button>
  <%= render  'shared/modal'%>
  <table class="table table-hover table-bordered mt-4 table-responsive{-sm|-md|-lg|-xl} ">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Measurement</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name%></td>
          <td><%= food.measurement_unit%></td>
          <td>$<%= food.price%></td>
          <td><%= food.quantity%></td>
          <td>
          <% if can? :destroy, food %>
          <%= button_to "Delete", food_path(food.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        <% end %>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>